### ISSUE TITLE
Installing on WSL2, so close!

### ISSUE THREAD

**Issue by paradisaeidae** [electrumsv/electrumsv-sdk#105]
So there may be a deal breaker with a limit of open files being imposed by MS-WSL2.
I did have to restart Win10 when node listener hampered '0.0.0.0 Permission....'
I might have tweeted too quickly.
Currently testing a VBox VM of similar Ubuntness to cross-check the issue:
Having installed electrumsv-sdk ok, without node RUNNING,
  - electrumx starts ok, waiting for node.
Then, start node,
  - electrumx crashes with issue in LevelDB.open
  - specifically within plyvel plyvel._plyvel.IOError: b'IO error: utxo: Invalid argument'
Without node running, no utxo directory, directory is created ok.
So there appears to be an issue with an attempt to update the database.
Permissions appear ok.
Being on the windows file system, checked for compression and encrytion, not set.
This is Python3.8 on Ubuntu 20.10
Using xorg electrumsv gui opens ok.
Have not found a way to use strace or step into plyvel extension.
As yet. Comming from Ruby.

**Comment by rt121212121** [comment]
I suspect this is a leveldb extension problem with WSL. Run directly on Windows with `py`. 

```
py -m pip install electrumsv-sdk
electrumsv-sdk ... whatever commands here ...
```
