### ISSUE TITLE
Ubuntu 21.04 upgrade, some adjustments required.

### ISSUE THREAD

**Issue by paradisaeidae** [electrumsv/electrumsv-sdk#106]
With little regard for my python3.8 install I upgraded my elsdk linux instance.
Some scratching around ensued.

Having upgraded to Ubuntu 21.04 you quite likely find python3.9 has been installed.
With a new modules directory.
Attempt to link this to 3.8 directory will not really help.
Re-install electrum-sdk.
Attempt to run will issue these symptoms. Possibly others.
Some modules require reinstall.

....electrumsv-sdk/remote_repos/electrumx/electrumx/lib/server_base.py
    server_task = await spawn(serve, report_crash=False)
TypeError: spawn() got an unexpected keyword argument 'report_crash'
Adjust with:
    server_task = await spawn(serve) #, report_crash=False)

....electrumsv-sdk/remote_repos/electrumx/electrumx/server/controller.py
If you see:
    raise RuntimeError('aiorpcX version 0.18.x is required')
 RuntimeError: aiorpcX version 0.18.x is required

pip uninstall aiorpcX
pip install aiorpcX==0.22
Comment out:
./.electrumsv-sdk/remote_repos/electrumx/electrumx/server/controller.py
   if not (0, 18, 1) <= aiorpcx_version < (0, 19):
       raise RuntimeError('aiorpcX version 0.18.x is required')

electrumsv-sdk install electrumsv   # May need re-install
apt-get install qtwayland5 # May assist!

**Comment by rt121212121** [comment]
Thanks for the feedback. I updated the dependencies to help ElectrumSV out, as they were clashing and did not see the electrumx problems myself.

The SDK should be on aiorpcX==0.22.1, to align with ElectrumSV, and the latest electrumx head is also at that version. I will try and find the time to update the SDK dependencies, and test it, to make sure it all works without these problems you had.

**Comment by rt121212121** [comment]
This should now be fixed.
