### ISSUE TITLE
SDK: Research windows firewall popup avoidance

### ISSUE THREAD

**Issue by rt121212121** [electrumsv/electrumsv-sdk#133]
Currently when starting a component which has not been given a firewall exception, for instance on first run of the given SDK component, the user has to deal with the confusing choice.

**Comment by rt121212121** [comment]
These are shown for at least "merchant_api", "node" and "header_sv". It is likely that it is binding the "0.0.0.0" interface needlessly rather than "127.0.0.1". We should make settings and configuration changes to avoid it, and consider whether we should make code changes if we have to (we edit/build all of these).

![image](https://user-images.githubusercontent.com/32600614/165197138-2342ddf3-7051-4a65-a00a-9c18faa9da92.png)

**Comment by AustEcon** [comment]
HeaderSV changed to localhost: https://github.com/electrumsv/electrumsv-sdk/commit/e70a718b4dd4c4ac2963c572f457a2ed3b341a96

**Comment by AustEcon** [comment]
I believe this is now resolved in the headless SDK. About to upload the latest release to github releases section for it.

**Comment by AustEcon** [comment]
@rt121212121 Latest release here to try at your convenience and see if the pop-ups are still happening for you with the node, Merchant API, HeaderSV
