### ISSUE TITLE
SDK: Merchant API reset errors

### ISSUE THREAD

**Issue by rt121212121** [electrumsv/electrumsv-sdk#135]
After a computer reset, in a Headless SDK install, just doing `electrumsv-sdk reset merchant_api` errors connecting to postgres. No previous runs have happened. Postgres is not installed and running.

It looks like the reset cannot handle lack of a running database from no previous runs.

**Comment by AustEcon** [comment]
I believe this will fix the problem https://github.com/electrumsv/electrumsv-sdk/commit/309b613c749330dbfdf2db13606ca384368d7e39 but will include it in a new headless_sdk release to be sure before closing
