### ISSUE TITLE
Upgrade gains simple_indexer ?

### ISSUE THREAD

**Issue by paradisaeidae** [electrumsv/electrumsv-sdk#143]
Am I reading through the lines when I see electrumx has been replaced by simple_indexer and reference_server?
Which might be a part of a recent release of elsdk?
Which I could upgrade with: pip install --upgrade electrumsv_sdk  ?
Which I'm nervous to do.
Will the indexer use the same RPC calls as electrumx?
Thanks!

**Comment by rt121212121** [comment]
Keep in mind we are actively developing 1.4.0 and we are not supporting wallet databases made with the `develop` branch. You should only use it to look at what we are doing, or contribute in development if you are interested. ElectrumX has not been replaced by the simple indexer, the simple indexer is only suitable for regtest development. We will be using commercial indexing services that provide an API we can use in place of simple indexer, on mainnet (and testnet and scaling testnet eventually).

It is not recommended to use PIP to manage the SDK. PIP is problematic. Use the [headless SDK releases](https://github.com/electrumsv/headless-sdk/releases), if you pursue this course and remember it is not ready for use.

Our master branch is out of date and no longer maintained. We do development in the `develop` branch. People should only use the `releases/1.3` branch.
