### ISSUE TITLE
SDK CLI - avoid starting and stopping ESV the first time merely to generate config files etc.

### ISSUE THREAD

**Issue by AustEcon** [electrumsv/electrumsv-sdk#36]
Instead could copy-paste the required files / create required directories (which should obviate a significant chunk of code and cut down on run time of pipelines tests.)

**Comment by rt121212121** [comment]
This is a bad idea. It means that any incompatible changes become roadblocks to progress.

**Comment by AustEcon** [comment]
Okay. Are you aware that it's only empty directories (cache, certs, wallets) that I'm copy-pasting and config is: 
```
    "config_version": 2,
    "rpcpassword": "",
    "rpcuser": "rpcuser"
```
There is no wallet database file or anything so the only time this would need to be updated would be if you altered the directory structure. But I take your point. It was just so awful though starting and stopping the ESV daemon in order to create the needed files/directories and then disable basic auth for the API!

BUT I think I can remove the copy-pasting as well if I fix this bug:
https://github.com/electrumsv/electrumsv/issues/111

Then can disable basic auth for the rest api AFTER initial launch of the daemon.

**Comment by rt121212121** [comment]
No, I was under the impression that the whole point was to pre-create a wallet to reuse in order to avoid doing it on-demand.

**Comment by AustEcon** [comment]
Okay cool 😃 

Still though - I would like to fix that bug one of these days to completely refactor this all away to nothing.
